### PR TITLE
Allow user to set a different database

### PR DESCRIPTION
**Pull request by SimonSimCity**
In my current project we need to connect to a different database, which I also want to have cleaned before every test run.

In this PR I allow the user to set his own database for the function `resetDatabase()`.

### CODE REVIEW

**Comment by SimonSimCity** [comment]
@samhatoum do you also have the permission to release a new version? 😊

**Comment by SamHatoum** [comment]
Gosh it's been so long I forgot how to do it! Let me take a look

**Comment by SimonSimCity** [comment]
You just need to check out the repository and run `meteor publish` - provided you already are logged in by running `meteor login`. Just make sure you don't have any files not part of the package inside the directory - like dev-dependencies.

**Comment by SamHatoum** [comment]
done @SimonSimCity. Thank you

**Pull request merged**
