### PR TITLE
Fix remove query causing tests to hang

### PR DESCRIPTION
**Pull request by FKint**

### CODE REVIEW

**Comment by FKint** [comment]
Related: #20

**Comment by juliedavila** [comment]
I've tested this locally and it also works for me.

**Comment by SamHatoum** [comment]
Thank you @FKint

**Comment by artgo** [comment]
@samhatoum @xolvio would it be possible to release new atmosphere package for this change? :)

**Comment by SamHatoum** [comment]
0.3.2 is out. Sorry, I thought I had done that but it had errored out

**Comment by juliedavila** [comment]
@samhatoum maybe it errored out again? I'm still getting `0.3.1` when trying to reinstall cleaner or upgrade it.

**Comment by juliedavila** [comment]
Ah, I see, it was a typo with your comment. The latest isn't `0.4.2` it is `0.3.2` which gets "upgraded" when you do it explicitly `meteor update xolvio:cleaner` which solves this issue.

Thanks

**Comment by SamHatoum** [comment]
oops, updated my comment. thank you

**Pull request merged**
