### PR TITLE
Add resetDatabase method

### LINKED ISSUE #4: Can't use on the client side?
I haven't tested this, but the code seems like it won't work on the client side because of [this line](https://github.com/xolvio/cleaner/blob/master/cleaner.js#L27). Meteor won't let an untrusted code use an arbitrary Mongo selector with `collection.remove`.

This might be a problem when doing client integration tests.

If that's the case, how about implementing something like this PR by @riebeekn?
https://github.com/sungwoncho/factory-boy/pull/3

### PR DESCRIPTION
**Pull request by sungwoncho**
fix #4

### CODE REVIEW

**Comment by sungwoncho** [comment]
Hmm.. calling the method throws because `process` is not available on the client side. Any ideas?

**Comment by ghost** [comment]
You need to add the cleaner.js file only on the server and remove the `if (Meteor.isClient)` condition. Then it should work. You define methods always on the server side and only additionally on the client side if you need a client method stub for latency compensation reasons. We don't need a client method stub in this case.

**Comment by ghost** [comment]
Also we may should namespace the method name to avoid conflicts. E.g. `xolvio:cleaner/resetDatabase`.

**Comment by ghost** [comment]
Fixed by #10

**Pull request closed without merging**
